/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_wang_hello_cpp_EHuman */

#ifndef _Included_com_example_wang_hello_cpp_EHuman
#define _Included_com_example_wang_hello_cpp_EHuman
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_wang_hello_cpp_EHuman
 * Method:    nInitMobilenet
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_wang_hello_cpp_EHuman_nInitMobilenet
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_example_wang_hello_cpp_EHuman
 * Method:    nDetectHuman
 * Signature: (Ljava/util/ArrayList;[BIIIZLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_wang_hello_cpp_EHuman_nDetectHuman
  (JNIEnv *, jclass, jobject, jbyteArray, jint, jint, jint, jboolean, jstring);

#ifdef __cplusplus
}
#endif
#endif
